exports.seed = async function (knex) {
  await knex('exercises').del();
  await knex('exercises').insert([
    {
      name: 'Incline barbell bench press',
      series: 4,
      repetitions: 12,
      group: 'chest',
      demo: 'supino_inclinado_com_barra.gif',
      thumb: 'supino_inclinado_com_barra.png',
    },
    {
      name: 'Butterfly',
      series: 3,
      repetitions: 12,
      group: 'chest',
      demo: 'crucifixo_reto.gif',
      thumb: 'crucifixo_reto.png',
    },
    {
      name: 'Barbel bench press',
      series: 3,
      repetitions: 12,
      group: 'chest',
      demo: 'supino_reto_com_barra.gif',
      thumb: 'supino_reto_com_barra.png',
    },
    {
      name: 'French press',
      series: 3,
      repetitions: 12,
      group: 'triceps',
      demo: 'frances_deitado_com_halteres.gif',
      thumb: 'frances_deitado_com_halteres.png',
    },
    {
      name: 'Triceps pushdown rope',
      series: 4,
      repetitions: 12,
      group: 'triceps',
      demo: 'corda_cross.gif',
      thumb: 'corda_cross.png',
    },
    {
      name: 'Triceps pushdown V bar',
      series: 3,
      repetitions: 12,
      group: 'triceps',
      demo: 'barra_cross.gif',
      thumb: 'barra_cross.png',
    },
    {
      name: 'Lying triceps extension',
      series: 4,
      repetitions: 12,
      group: 'triceps',
      demo: 'triceps_testa.gif',
      thumb: 'triceps_testa.png',
    },
    {
      name: 'Deadlift',
      series: 3,
      repetitions: 12,
      group: 'back',
      demo: 'levantamento_terra.gif',
      thumb: 'levantamento_terra.png',
    },
    {
      name: 'Front lat pulldowns',
      series: 3,
      repetitions: 12,
      group: 'back',
      demo: 'pulley_frontal.gif',
      thumb: 'pulley_frontal.png',
    },
    {
      name: 'Rear çat pulldowns',
      series: 4,
      repetitions: 12,
      group: 'back',
      demo: 'pulley_atras.gif',
      thumb: 'pulley_atras.png',
    },
    {
      name: 'Seated low row',
      series: 4,
      repetitions: 12,
      group: 'back',
      demo: 'remada_baixa.gif',
      thumb: 'remada_baixa.png',
    },
    {
      name: 'One arm dumbbel bent over row',
      series: 4,
      repetitions: 12,
      group: 'back',
      demo: 'serrote.gif',
      thumb: 'serrote.png',
    },
    {
      name: 'Incline bench alternate dumbbel bicep curl',
      series: 4,
      repetitions: 12,
      group: 'biceps',
      demo: 'rosca_alternada_com_banco_inclinado.gif',
      thumb: 'rosca_alternada_com_banco_inclinado.png',
    },
    {
      name: 'Scott curl EZ bar',
      series: 4,
      repetitions: 12,
      group: 'biceps',
      demo: 'rosca_scott_barra_w.gif',
      thumb: 'rosca_scott_barra_w.png',
    },
    {
      name: 'Straight bar bicep curl',
      series: 3,
      repetitions: 12,
      group: 'biceps',
      demo: 'rosca_direta_barra_reta.gif',
      thumb: 'rosca_direta_barra_reta.png',
    },
    {
      name: 'Hammer curl',
      series: 3,
      repetitions: 12,
      group: 'biceps',
      demo: 'martelo_em_pe.gif',
      thumb: 'martelo_em_pe.png',
    },
    {
      name: 'Wrist curl',
      series: 4,
      repetitions: 12,
      group: 'forearm',
      demo: 'rosca_punho.gif',
      thumb: 'rosca_punho.png',
    },
    {
      name: 'Leg press 45 degrees',
      series: 4,
      repetitions: 12,
      group: 'legs',
      demo: 'leg_press_45_graus.gif',
      thumb: 'leg_press_45_graus.png',
    },
    {
      name: 'Leg extension',
      series: 4,
      repetitions: 12,
      group: 'legs',
      demo: 'extensor_de_pernas.gif',
      thumb: 'extensor_de_pernas.png',
    },
    {
      name: 'Leg abduction',
      series: 4,
      repetitions: 12,
      group: 'legs',
      demo: 'abdutora.gif',
      thumb: 'abdutora.png',
    },
    {
      name: 'Stiff',
      series: 4,
      repetitions: 12,
      group: 'legs',
      demo: 'stiff.gif',
      thumb: 'stiff.png',
    },
    {
      name: 'Neck Press',
      series: 4,
      repetitions: 10,
      group: 'shoulder',
      demo: 'neck-press.gif',
      thumb: 'neck-press.png',
    },
    {
      name: 'Shoulder press',
      series: 3,
      repetitions: 10,
      group: 'shoulder',
      demo: 'desenvolvimento_maquina.gif',
      thumb: 'desenvolvimento_maquina.png',
    },
    {
      name: 'Seated dumbbell side lateral raise',
      series: 4,
      repetitions: 10,
      group: 'shoulder',
      demo: 'elevacao_lateral_com_halteres_sentado.gif',
      thumb: 'elevacao_lateral_com_halteres_sentado.png',
    },
    {
      name: 'Dumbbells shrug',
      series: 4,
      repetitions: 10,
      group: 'trapezius',
      demo: 'encolhimento_com_halteres.gif',
      thumb: 'encolhimento_com_halteres.png',
    },
    {
      name: 'Barbell shrug',
      series: 4,
      repetitions: 10,
      group: 'trapezius',
      demo: 'encolhimento_com_barra.gif',
      thumb: 'encolhimento_com_barra.png',
    },
  ]);
};
